// <auto-generated />
using System;
using CarsCrudWithPagination.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsCrudWithPagination.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    [Migration("20241021090638_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarsCrudWithPagination.Models.Car", b =>
                {
                    b.Property<int>("CarNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarNo"));

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColorNo")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarNo");

                    b.HasIndex("ColorNo");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarNo = 1,
                            ArName = "اول اسم",
                            BeginDate = new DateTime(2024, 10, 21, 12, 6, 37, 935, DateTimeKind.Local).AddTicks(3378),
                            CardNo = "33",
                            ColorNo = 1,
                            Company = "Appy",
                            EnName = "First Name",
                            EndDate = new DateTime(2024, 10, 26, 12, 6, 37, 935, DateTimeKind.Local).AddTicks(3425),
                            Model = "bmw",
                            UserNo = "1"
                        },
                        new
                        {
                            CarNo = 2,
                            ArName = "ثاني اسم",
                            BeginDate = new DateTime(2024, 10, 21, 12, 6, 37, 935, DateTimeKind.Local).AddTicks(3433),
                            CardNo = "33",
                            ColorNo = 2,
                            Company = "mg",
                            EnName = "Second Name",
                            EndDate = new DateTime(2024, 10, 31, 12, 6, 37, 935, DateTimeKind.Local).AddTicks(3435),
                            Model = "bmw",
                            UserNo = "2"
                        },
                        new
                        {
                            CarNo = 3,
                            ArName = "ثالث اسم",
                            BeginDate = new DateTime(2024, 10, 21, 12, 6, 37, 935, DateTimeKind.Local).AddTicks(3438),
                            CardNo = "33",
                            ColorNo = 3,
                            Company = "mg-control.com",
                            EnName = "Third Name",
                            EndDate = new DateTime(2024, 11, 5, 12, 6, 37, 935, DateTimeKind.Local).AddTicks(3440),
                            Model = "mg",
                            UserNo = "3"
                        });
                });

            modelBuilder.Entity("CarsCrudWithPagination.Models.Colors", b =>
                {
                    b.Property<int>("ColorNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorNo"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorNo");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorNo = 1,
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorNo = 2,
                            ColorName = "Black"
                        },
                        new
                        {
                            ColorNo = 3,
                            ColorName = "Green"
                        });
                });

            modelBuilder.Entity("CarsCrudWithPagination.Models.Car", b =>
                {
                    b.HasOne("CarsCrudWithPagination.Models.Colors", "Color")
                        .WithMany()
                        .HasForeignKey("ColorNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });
#pragma warning restore 612, 618
        }
    }
}
